### ISSUE TITLE
The source code does not have the OPENSSL_DIR directory

### ISSUE THREAD

**Issue by QuzhouSmallDragon** [Creel6/prime-probe-aes#1]
which version of openssl are you using

**Comment by ukouji** [comment]
Latest version but compile with no-asm flag. 'OPENSSL_DIR' is just a place holder for your custom openssl directory.

**Comment by QuzhouSmallDragon** [comment]
您好，
我前面的步骤都顺利通过了，在Attack Environment最后一步执行setup.sh脚本时出现下面的错误。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kreelsama/prime-probe-aes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 晚上7:35
收件人:&nbsp;"kreelsama/prime-probe-aes"<prime-probe-aes@noreply.github.com&gt;;
抄送:&nbsp;"664239723"<664239723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kreelsama/prime-probe-aes] The source code does not have the OPENSSL_DIR directory (#1)





 
Latest version but compile with no-asm flag. 'OPENSSL_DIR' is just a place holder for your custom openssl directory.

**Comment by QuzhouSmallDragon** [comment]
In the Attack Environment step,I excute setup.sh,the output is:
Start Counters
./setup.sh:line 3:./pmctest: cannot execute binary file: Exec format error 
I can't know how to solve it.

**Comment by ukouji** [comment]
Do you recompile the source files in /pmc_events/?

**Comment by QuzhouSmallDragon** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kreelsama/prime-probe-aes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 下午2:59
收件人:&nbsp;"kreelsama/prime-probe-aes"<prime-probe-aes@noreply.github.com&gt;;
抄送:&nbsp;"664239723"<664239723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kreelsama/prime-probe-aes] The source code does not have the OPENSSL_DIR directory (#1)





 
Do you recompile the source files in /pmc_events/?

**Comment by ukouji** [comment]
Do you try to execute make clean before make? If the error persists, please post your CPU info, platform details and compiler version.
