### ISSUE TITLE
How to set the values of 'CPU0' and 'CPU1' in 'common.h'

### ISSUE THREAD

**Issue by Nakuro1999** [Creel6/prime-probe-aes#2]
I'm sorry I can't understand the attacker and victim.Waht's the meaning of the attacker and victim？Can I set the attacker and victim to the same host？And how to set the values of 'CPU0' and 'CPU1' in 'common.h'

**Comment by ukouji** [comment]
Your CPU has to support simultaneous multithreading(SMT) to run this code. 
And attacker and victim thread should be running in the same cpu core separately and continuously to share the L1D cache. If you let attacker and victim threads run in one CPU logical core, the context switch will pollute the L1d and render the attack impossible. 

To set CPU0 and CPU1, you can check the `/proc/cpuinfo` file for the two `processor` numbers with same `core id.`
